### ISSUE TITLE
Problem with integration in nuxt 2 project.

### ISSUE THREAD

**Issue by ThornWalli** [codepunkt/webpack-license-plugin#1072]
Hello,

I am currently trying to install the plugin in a Nuxt 2 project.

Node: 18.16.0
Nuxt: 2.16.3
Webpack 4 should be in use.

```
{
  build: {
    plugins: [
      new LicensePlugin({ outputFilename: 'thirdPartyNotice.json' })
    ],
  }
}
```

Unfortunately I get this error during the build:

```
 ERROR  Cannot read properties of undefined (reading 'RawSource')                                                                                                       9:59:32 AM

  at e (xxx/node_modules/webpack-license-plugin/dist/index.cjs:1:16574)
  at xxx/node_modules/webpack-license-plugin/dist/index.cjs:1:4945
  at u (xxx/node_modules/webpack-license-plugin/dist/index.cjs:1:2995)
  at Object.next (xxx/node_modules/webpack-license-plugin/dist/index.cjs:1:2286)
  at r (xxx/node_modules/webpack-license-plugin/dist/index.cjs:1:191)
  at s (xxx/node_modules/webpack-license-plugin/dist/index.cjs:1:402)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

What could be the reason for this?

**Comment by codepunkt** [comment]
I'm not sure.
Does this still happen with the latest version of this plugin?
Do you have a reproducible example?
