### ISSUE TITLE
How to use with next.js?

### ISSUE THREAD

**Issue by fhg-isi** [codepunkt/webpack-license-plugin#914]
I tried following next.config.js

```
const LicensePlugin = require('webpack-license-plugin');

const nextConfig = {
  // If you change the basePaths, also change path for favicon in _document.js
  basePath: '/mica-tool-wGlobal/python/front_end/out',
  reactStrictMode: true,
  images: {
    unoptimized: true // required for static export to work
  },
  webpack: (config) => {
    config.resolve.fallback = {
      'fs': false
    };

    config.plugins = [new LicensePlugin()]

    return config;
  }

};

// eslint-disable-next-line unicorn/prefer-module
module.exports = nextConfig;
```

and got

```
npm run build

> micat@0.0.1 build
> next build && next export

- info Linting and checking validity of types  
- info Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.json" https://nextjs.org/docs/messages/swc-disabled
(node:17744) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
Failed to compile.

./node_modules/next/dist/pages/_app.js
TypeError: Cannot read properties of undefined (reading 'traceChild')
    at Object.nextBabelLoaderOuter (C:\python_env\workspace\micat\front_end\node_modules\next\dist\build\babel\loader\index.js:31:46)

./node_modules/next/dist/pages/_document.js
TypeError: Cannot read properties of undefined (reading 'traceChild')
    at Object.nextBabelLoaderOuter (C:\python_env\workspace\micat\front_end\node_modules\next\dist\build\babel\loader\index.js:31:46)

./node_modules/next/dist/pages/_error.js
TypeError: Cannot read properties of undefined (reading 'traceChild')
    at Object.nextBabelLoaderOuter (C:\python_env\workspace\micat\front_end\node_modules\next\dist\build\babel\loader\index.js:31:46)

Import trace for requested module:
./node_modules/next/dist/pages/_error.js

./src/pages/[id-mode]/[id-region]/index.js
TypeError: Cannot read properties of undefined (reading 'traceChild')
    at Object.nextBabelLoaderOuter (C:\python_env\workspace\micat\front_end\node_modules\next\dist\build\babel\loader\index.js:31:46)

Import trace for requested module:
./src/pages/[id-mode]/[id-region]/index.js

HookWebpackError: Cannot read properties of undefined (reading 'traceChild')
    at makeWebpackError (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:28:311139)
    at C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:28:105980
    at eval (eval at create (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:58:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
-- inner error --
TypeError: Cannot read properties of undefined (reading 'traceChild')
    at TerserPlugin.optimize (C:\python_env\workspace\micat\front_end\node_modules\next\dist\build\webpack\plugins\terser-webpack-plugin\src\index.js:92:44)
    at C:\python_env\workspace\micat\front_end\node_modules\next\dist\build\webpack\plugins\terser-webpack-plugin\src\index.js:259:31
    at fn (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:28:69698)
    at _next0 (eval at create (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:50:17)
    at eval (eval at create (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:66:1)
    at eval (eval at create (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:11:1)
    at C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:28:69336
    at Hook.eval [as callAsync] (eval at create (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:13:26021)
    at C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:28:69505
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read properties of undefined (reading 'traceChild')
    at TerserPlugin.optimize (C:\python_env\workspace\micat\front_end\node_modules\next\dist\build\webpack\plugins\terser-webpack-plugin\src\index.js:92:44)
    at C:\python_env\workspace\micat\front_end\node_modules\next\dist\build\webpack\plugins\terser-webpack-plugin\src\index.js:259:31
    at fn (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:28:69698)
    at _next0 (eval at create (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:50:17)
    at eval (eval at create (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:66:1)
    at eval (eval at create (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:11:1)
    at C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:28:69336
    at Hook.eval [as callAsync] (eval at create (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:13:28867), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:13:26021)
    at C:\python_env\workspace\micat\front_end\node_modules\next\dist\compiled\webpack\bundle5.js:28:69505


> Build failed because of webpack errors
- info Creating an optimized production build .
```

Without the extra plugin entry `npm run build` works fine.

**Comment by codepunkt** [comment]
@fhg-isi Afaik `next` already uses webpack plugins, so the way you'd use add this plugin is this - which we're using successfully with the latest `next` major version at @cosuno:

```js
const nextConfig = {
  webpack: (config, { dev }) => {
      // Add OSS license information to production bundle
      if (!dev) {
        const WebpackLicensePlugin = require('webpack-license-plugin');
        config.plugins.push(new WebpackLicensePlugin(/* options */))
      }

      return config;
    },
};
```
