### ISSUE TITLE
DeprecationWarning: optimizeChunkAssets is deprecated 

### ISSUE THREAD

**Issue by hbroer** [codepunkt/webpack-license-plugin#915]
I get a deprecation warning which looks like it is caused by `webpack-license-plugin`:

```
(node:16600) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
    at WebpackLicensePlugin.handleCompilation ([...]\node_modules\webpack-license-plugin\src\WebpackLicensePlugin.ts:70:45)
    at Hook.eval (eval at create ([...]\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] ([...]\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation ([...]\node_modules\webpack\lib\Compiler.js:1126:26)
    at [...]\node_modules\webpack\lib\Compiler.js:1170:29
    at Hook.eval [as callAsync] (eval at create ([...]\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] ([...]\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile ([...]\node_modules\webpack\lib\Compiler.js:1165:28)
    at [...]\node_modules\webpack\lib\Compiler.js:524:12
    at Compiler.readRecords ([...]\node_modules\webpack\lib\Compiler.js:989:5)
```

Plugin is used without options: 

```
{
  ... 
  plugins: [new HtmlWebpackPlugin(), new LicensePlugin()],
}
```

# Versions

All up to date.

webpack: 5.88.2 
webpack-license-plugin: 4.2.2

**Comment by codepunkt** [comment]
@hbroer Thanks! There's a new version `4.2.3` that I've just released. Can you check if you still receive those deprecation warnings?

**Comment by scholtzm** [comment]
@codepunkt We experienced the same warning and it's gone now, thanks!

**Comment by hbroer** [comment]
Forgot to answer after we updated the plugin. Yes it is gone. Thanks!
